# Generated by Django 4.1.7 on 2023-02-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='id_servico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
