# Generated by Django 4.1.7 on 2023-02-23 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicosapp', '0002_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 17, 42, 30, 211388, tzinfo=datetime.timezone.utc), verbose_name='Data de publicação'),
        ),
    ]
