# Generated by Django 4.1.7 on 2023-02-23 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicosapp', '0003_servico_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 17, 48, 28, 859750, tzinfo=datetime.timezone.utc), verbose_name='Data de publicação'),
        ),
    ]
