# Generated by Django 4.1.7 on 2023-02-23 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicosapp', '0005_alter_servico_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='fk_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicosapp.categoria'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servico',
            name='telefone_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='telefone_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
