# Generated by Django 4.1.7 on 2023-03-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicosapp', '0006_servico_preco_alter_servico_data_pub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_municipio', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='fk_municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicosapp.municipio'),
        ),
    ]
